import { Inter } from "next/font/google";
import "./globals.css";
import Image from 'next/image'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className='container'>
          {children}
        </div>

        <footer>

          <div className="footer-div">

            <div className="footer-div-inner active">
              <Image
                src={"/assests/home.png"}
                width={25}
                height={25}
                alt='home'
              />

              <p className="footer-pgh">
                Home
              </p>
            </div>

            <div className="footer-div-inner">
              <Image
                src={"/assests/compass.png"}
                width={25}
                height={25}
                alt='compass'
              />

              <p className="footer-pgh">
                Activity
              </p>
            </div>

            <div className="footer-div-inner">
              <Image
                src={"/assests/list.png"}
                width={25}
                height={25}
                alt='History'
              />

              <p className="footer-pgh">
                History
              </p>
            </div>

            <div className="footer-div-inner">
              <Image
                src={"/assests/settings.png"}
                width={25}
                height={25}
                alt='Settings'
              />

              <p className="footer-pgh">
                Settings
              </p>
            </div>

          </div>

        </footer>

      </body>
    </html>
  );
}
